name: 'ZapTests'
description: 'Run API tests, version comparison, stress testing, assertion testing using a custom API testing tool which not only integrates with your CI/CD pipeline but also generates descriptive reports.'
author: 'Moonshrine'
inputs:
  runType:
    description: 'Type of test to run'
    required: true
    default: 'ComparisonTest'
  baselineEnv:
    description: 'Baseline Env'
    required: false
  undertestEnv:
    description: 'Undertest Env'
    required: false
  testEnv:
    description: 'Test env'
    required: false
  runSettingsLocation:
    description: 'Runsettings json file path'
    required: true
  testsuitsLocation:
    description: 'Location of test suits'
    required: true
  outputLocation:
    description: 'Output folder to save the reports'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run ZapTests tool
      shell: bash
      run: |
        chmod +x ./ZapTests.exe
        ./ZapTests.exe --RunType ${{ inputs['runType'] }} --BaselineEnv ${{ inputs['baselineEnv'] }} --UnderTestEnv ${{ inputs['undertestEnv'] }} --TestEnv ${{ inputs['testEnv'] }} --RunSettingsPath ${{ inputs['runSettingsLocation'] }} --TestSuitsPath ${{ inputs['testsuitsLocation'] }} --OutputPath ${{ inputs['outputLocation'] }}
branding:
  icon: 'check-circle'
  color: 'blue'
